name = "FolderMap"
license = "MIT"
licenselink = ""
description = "Maps folder to website structure"
tags = []
features = []

[author]
    name = "Jannik Arndt"
    homepage = "https://github.com/JannikArndt"

[original]
    name = "MenuMenu"
    author = "Valere JEANTET"
    repo = "https://github.com/vjeantet/hugo-menu-show/"
    homepage = "http://vjeantet.github.io/hugo-menu-show/"